<a href="https://colab.research.google.com/github/flanaganc04/My-own-Neural-Net/blob/main/Digit_Recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import packages
from google.colab import drive
import os
import datetime
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random

In [ ]:
# Mount Google Drive and try not to get yelled at
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import data
train_data = pd.read_csv('/content/drive/MyDrive/Digit Recognizer/mnist_test.csv')
test_data = pd.read_csv('/content/drive/MyDrive/Digit Recognizer/mnist_train.csv')
X_train = train_data.iloc[:, 2:-1]  # Features
X_train_np = X_train.to_numpy()
# print(X_train)
Y_train = test_data.iloc[:, 0]   # Target variable
Y_train_np = Y_train.to_numpy()
# print(Y_train)
X_test = test_data.iloc[:, 2:-1]  # Features
X_test_np = X_test.to_numpy()
# print(X_test)
Y_test = test_data.iloc[:, 0]   # Target variable
Y_test_np = Y_test.to_numpy()
# print(Y_test)

In [ ]:
# Make a Weight Matrix of random values between 0-1. The grayscale values are between 0-255. If this needs to be a larger value than we can change the random function's bounds.
weightMatrix = np.ones(shape=X_train.shape)
# print(weightMatrix)
for row in range(weightMatrix.shape[0]):
  for column in range(weightMatrix.shape[1]):
    weightMatrix[row][column] = random.random()
# print(weightMatrix)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[[0.01908403 0.90918571 0.93786958 ... 0.82115812 0.91016108 0.42782661]
 [0.31485667 0.11290535 0.01444155 ... 0.72712966 0.85452054 0.43448689]
 [0.30546036 0.95414418 0.13975122 ... 0.48089571 0.29348348 0.1641993 ]
 ...
 [0.98118544 0.04154033 0.21992921 ... 0.26680357 0.20145791 0.98044492]
 [0.29635387 0.09758601 0.64649326 ... 0.19291603 0.10360904 0.72935338]
 [0.04541226 0.05260132 0.50386961 ... 0.31804724 0.82027132 0.26209924]]


In [ ]:
biasMatrix = np.ones(shape=(10000,1))
print(biasMatrix)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]


In [ ]:
# Create a temporary matrix to hold some stuff, mainly, we are multiplying all the inputs by all of their respective weights
tempMatrix = np.ones(shape=X_train.shape)
# print(tempMatrix)
for row in range(X_train.shape[0]):
  for column in range(X_train.shape[1]):
    tempMatrix[row][column] = X_train_np[row][column] * weightMatrix[row][column]



In [ ]:
newTempMatrix = np.zeros(shape=(10000,1))
# print(newTempMatrix)
for row in range(tempMatrix.shape[0]):
  tempValue=0
  for column in range(tempMatrix.shape[1]):
    tempValue += tempMatrix[row][column]
  newTempMatrix[row][0] = tempValue
# print(newTempMatrix)

In [ ]:
  outputMatrix = np.zeros(shape=(10000,1))
  for row in range(newTempMatrix.shape[0]):
    outputMatrix[row][0] = newTempMatrix[row][0] + biasMatrix[row][0]
  print(outputMatrix)

[[ 8714.31625865]
 [15242.14576742]
 [ 4632.9927989 ]
 ...
 [14573.57687919]
 [13097.50307593]
 [22285.26028529]]
